# Generated by Django 5.0.1 on 2026-02-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_file_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
